new_sites:
    eluniversal:
        url: http://eluniversal.com.mx
        queries:
            home_page_article_links: '.field-content a'
            article_body: '.field-name-body'
            article_title: '.pane-content h1'
    elpais:
        url: http://elpais.com.mx
        queries:
            home_page_article_links: ''
            article_body: ''
            article_title: ''